FROM node:6.10.0-slim

WORKDIR /src
ADD . /src

ADD . /src/server

# Install dependencies
RUN cd server && npm install

# Expose port
EXPOSE  3000

WORKDIR /src/server

# Run app
CMD ["node", "server.js"]